baseURL = 'https://piot5.github.io/devs_log/'
languageCode = 'en-us'
title = "Dev's Log"
theme = 'paper'

# Automatische Bereinigung des Zielverzeichnisses bei jedem Build
cleanDestinationDir = true

[params]
    author = "piot5"
    description = "A developer's log about coding, engines, and logic."
    showReadingTime = true
    # Globale Projekt-Links
    github_repo = "https://github.com/piot5/displayflow"
    landing_page = "https://piot5.github.io/displayflow_cli/"

[[params.social]]
    name = "github"
    url = "https://github.com/piot5"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    style = 'github-dark'
    noClasses = true
  [markup.goldmark.renderer]
    unsafe = true # Ermöglicht HTML-Elemente in Markdown-Dateien

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 10

[[menu.main]]
    name = "Posts"
    url = "/posts"
    weight = 20